// <auto-generated />
namespace Api.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CratepersonnelModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CratepersonnelModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201809030340309_Crate personnelModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
